# Generated by Django 5.2.1 on 2025-05-29 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_description_alter_product_id_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b7be77ab-31b9-4961-b532-7349122ad736'), primary_key=True, serialize=False),
        ),
    ]
