# Generated by Django 5.2.1 on 2025-05-29 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_logo_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fccf4dc-8845-494b-8184-aa7ad6750e0b'), primary_key=True, serialize=False),
        ),
    ]
