# Generated by Django 5.2.1 on 2025-05-29 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_slug_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44b7278b-9a64-47ba-abc9-df4d68176bd9'), primary_key=True, serialize=False),
        ),
    ]
